repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
      - id: reorder-python-imports
  - repo: local
    hooks:
      - id: "unit-tests"
        name: "Run unit tests (tests/unit/)"
        entry: uv run pytest tests/unit/ --tb=short -q
        language: system
        pass_filenames: false
      - id: "ArenaX-broker-integration-test"  # We skip the sinopac integration test
        name: "Run integration test: ArenaX (tests/integration/arenax/)"
        entry: bash tests/run_broker_stability_tests.sh --broker=arenax
        language: system
        pass_filenames: false
      - id: "arenax-shell"
        name: "Run CJTrade shell test: ArenaX"
        entry: uv run atest --broker=arenax --group=all
        language: system
        pass_filenames: false
      - id: "sinopac-shell"
        name: "Run CJTrade shell test: Sinopac"
        entry: uv run test --broker=sinopac --group=all
        language: system
        pass_filenames: false
