@echo off
setlocal

:: current supported templates: mock, sinopac
set "TEMPLATE=%~1"

if "%TEMPLATE%"=="" (
    echo Usage: %~nx0 ^<template^>
    echo Supported templates: [mock, sinopac]
    exit /b 1
)

set "OUTPUT_PATH=%TEMPLATE%_system.cjconf"

call :main
exit /b %errorlevel%

:: ---------------- Functions ----------------

:create_file
if exist "%OUTPUT_PATH%" (
    set /p choice=File %OUTPUT_PATH% already exists. overwrite? (y/n)
    if /I "%choice%"=="n" (
        echo Aborting.
        exit /b 1
    )
)

(
echo # CJTrade system configuration file: %OUTPUT_PATH%
echo #   Auto-generated by scripts/gen_config.sh with template: %TEMPLATE%
echo #   Some of the configuration items like API_KEY are intentionally
echo #   left blank for you to fill in later.
echo.
) > "%OUTPUT_PATH%"

exit /b 0

:: ---------- FIXED PART ----------
:write_line
if "%~1"=="" (
    echo.>>"%OUTPUT_PATH%"
) else (
    echo %~1>>"%OUTPUT_PATH%"
)
exit /b 0
:: ---------------------------------

:generate_mock_config
call :write_line "# Broker-specific configuration"
call :write_line "API_KEY = MOCK_BROKER_DOES_NOT_REQUIRE_AN_API_KEY"
call :write_line "SECRET_KEY = MOCK_BROKER_DOES_NOT_REQUIRE_A_SECRET_KEY"
call :write_line "CA_CERT_PATH = "
call :write_line "CA_PASSWORD = "
call :write_line ""

call :write_line "# Mock-environment-specific configuration"
call :write_line "MOCK_PLAYBACK_SPEED = 60"
call :write_line "MOCK_MARKET_MATCH_METHOD = lazy"
call :write_line ""

call :write_line "# LLM-specific configuration"
call :write_line "LLM_MODEL = gemini-3-flash"
call :write_line "LLM_API_KEY = "
call :write_line "GEMINI_API_KEY = "

echo ---- Note start ----
echo Get your Gemini API key at https://aistudio.google.com/app/api-keys
echo Most of the features do not require a LLM backend,
echo so you can skip this right now and fill it in later
echo ----  Note end  ----

echo Mock configuration generated at %OUTPUT_PATH%
exit /b 0

:generate_sinopac_config
call :write_line "# Broker-specific configuration"
call :write_line "API_KEY = "
call :write_line "SECRET_KEY = "
call :write_line "CA_CERT_PATH = "
call :write_line "CA_PASSWORD = "
call :write_line "SIMULATION = n  # to see your real account status."
call :write_line ""

echo ---- Note start ----
echo Get your Sinopac api key / secret key / ca cert at https://ai.sinotrade.com.tw/python/Main/index.aspx#pag4
echo These information is required to connect to Sinopac broker.
echo Currently we do not support auto configuration of these information, so you need to fill them in manually later on.
echo ----  Note end  ----

call :write_line "# LLM-specific configuration"
call :write_line "LLM_MODEL = gemini-3-flash"
call :write_line "LLM_API_KEY = "
call :write_line "GEMINI_API_KEY = "

echo ---- Note start ----
echo Get your Gemini API key at https://aistudio.google.com/app/api-keys
echo Most of the features do not require a LLM backend,
echo so you can skip this right now and fill it in later
echo ----  Note end  ----

echo Sinopac configuration generated at %OUTPUT_PATH%
exit /b 0

:main
call :create_file || exit /b 1

if /I "%TEMPLATE%"=="mock" (
    call :generate_mock_config
) else if /I "%TEMPLATE%"=="sinopac" (
    call :generate_sinopac_config
) else (
    echo Unsupported template: %TEMPLATE%
    exit /b 1
)

exit /b 0
