#!/bin/bash

# current supported templates: mock, sinopac
TEMPLATE=$1
OUTPUT_PATH="${TEMPLATE}_system.cjconf"

function create_file() {
    if [ -f "$OUTPUT_PATH" ]; then
        read -p "File $OUTPUT_PATH already exists. overwrite? (y/n)" choice
        if [ "$choice" == "n" ]; then
            echo "Aborting."
            exit 1
        fi
    fi
    echo "# CJTrade system configuration file: $OUTPUT_PATH" > "$OUTPUT_PATH"
    echo "#   Auto-generated by scripts/gen_config.sh with template: $TEMPLATE" >> "$OUTPUT_PATH"
    echo "#   Some of the configuration items like API_KEY are intentionally" >> "$OUTPUT_PATH"
    echo "#   left blank for you to fill in later." >> "$OUTPUT_PATH"
    echo "" >> "$OUTPUT_PATH"
}

function write_line() {
    echo "$1" >> "$OUTPUT_PATH"
}

function generate_mock_config() {
    write_line "# Broker-specific configuration"
    write_line "API_KEY = MOCK_BROKER_DOES_NOT_REQUIRE_AN_API_KEY"
    write_line "SECRET_KEY = MOCK_BROKER_DOES_NOT_REQUIRE_A_SECRET_KEY"
    write_line "CA_CERT_PATH = "
    write_line "CA_PASSWORD = "
    write_line ""

    write_line "# Mock-environment-specific configuration"
    write_line "MOCK_PLAYBACK_SPEED = 60"
    write_line "MOCK_MARKET_MATCH_METHOD = lazy"
    write_line ""

    write_line "# LLM-specific configuration"
    write_line "LLM_MODEL = gemini-3-flash"
    write_line "LLM_API_KEY = "
    write_line "GEMINI_API_KEY = "

    echo "---- Note start ----"
    echo "Get your Gemini API key at https://aistudio.google.com/app/api-keys"
    echo "Most of the features do not require a LLM backend,"
    echo "so you can skip this right now and fill it in later"
    echo "----  Note end  ----"

    echo "Mock configuration generated at $OUTPUT_PATH"
}

function generate_sinopac_config() {
    write_line "# Broker-specific configuration"
    write_line "API_KEY = "
    write_line "SECRET_KEY = "
    write_line "CA_CERT_PATH = "
    write_line "CA_PASSWORD = "
    write_line "SIMULATION = n  # to see your real account status."
    write_line ""

    echo "---- Note start ----"
    echo "Get your Sinopac api key / secret key / ca cert at https://ai.sinotrade.com.tw/python/Main/index.aspx#pag4"
    echo "These information is required to connect to Sinopac broker."
    echo "Currently we do not support auto configuration of these information, so you need to fill them in manually later on."
    echo "----  Note end  ----"

    write_line "# LLM-specific configuration"
    write_line "LLM_MODEL = gemini-3-flash"
    write_line "LLM_API_KEY = "
    write_line "GEMINI_API_KEY = "

    echo "---- Note start ----"
    echo "Get your Gemini API key at https://aistudio.google.com/app/api-keys"
    echo "Most of the features do not require a LLM backend,"
    echo "so you can skip this right now and fill it in later"
    echo "----  Note end  ----"

    echo "Mock configuration generated at $OUTPUT_PATH"
}

if [ -z "$TEMPLATE" ]; then
    echo "Usage: $0 <template>"
    echo "Supported templates: [mock, sinopac]"
    exit 1
fi

function main() {
    create_file
    if [ "$TEMPLATE" == "mock" ]; then
        generate_mock_config
    elif [ "$TEMPLATE" == "sinopac" ]; then
        generate_sinopac_config
    else
        echo "Unsupported template: $TEMPLATE"
        exit 1
    fi
}

main