from cjtrade.pkgs.llm._llm_base import LLMClientBase
# User's LLM pool (a set of available LLMs for fallback plan)

class LLMPool(LLMClientBase):
    def __init__(self, llms: list[LLMClientBase]):
        self.llms = llms
        self.current_index = 0

    def get_current_llm(self):
        if not self.llms:
            raise Exception("No LLMs available in the pool.")
        return self.llms[self.current_index]

    def get_next_llm(self):
        if not self.llms:
            raise Exception("No LLMs available in the pool.")
        next_index = (self.current_index + 1) % len(self.llms)
        return self.llms[next_index]

    def generate_response(self, prompt):
        current_llm = self.get_current_llm()
        response = None
        while response is None:
            try:
                response = current_llm.generate_response(prompt)
            except Exception as e:
                print(f"Error with LLM {current_llm}: {e}. Falling back to next LLM.")
                self._fallback()
                current_llm = self.get_current_llm()
        print(f"Response generated by LLM {current_llm}.")
        return response

    def _fallback(self):
        if not self.llms:
            raise Exception("No LLMs available in the pool.")
        self.current_index = (self.current_index + 1) % len(self.llms)
